server:
  port: 8081
spring:
  application:
    name: dgca-verifier-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/dgc
#    username: root
#    password: P@ssw0rd
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jndi-name: false
#    jpa:
#      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.xml
  h2:
    console:
      enabled: true
      path: /h2-console
  task:
    scheduling:
      pool:
        size: 5
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health
info:
  name: ${spring.application.name}
  profiles: ${spring.profiles.active}
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
dgc:
  certificatesDownloader:
    timeInterval: 60000
    lockLimit: 1800000
  gateway:
    connector:
      enabled: true
      endpoint: http://thai-dgc.digio.co.th:8090
      proxy:
        enabled: false
      max-cache-age: 300
      tls-trust-store:
        password:
        path: classpath:tls_trust_store.p12
      tls-key-store:
        alias: 1
        password:
        path: classpath:tls_key_store.p12
      trust-anchor:
        alias: dgcg_trust_anchor
        password: dgcg-p4ssw0rd
        path: classpath:ta.jks
