name: Dependency Check (OWASP)
on:
  schedule:
    - cron: '32 05 * * 0' # Each Sunday at 05:32 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: s4u/maven-settings-action@v2.4.0
        with:
          githubServer: false
          servers: |
            [
              {
                "id": "dgc-github",
                "username": "${{ secrets.GPR_USER }}",
                "password": "${{ secrets.GPR_PAT }}"
              }
            ]
      - name: Execute Dependency Check
        run: mvn --batch-mode dependency-check:check
